"""Foo Table

Revision ID: cb55c7d02aa0
Revises: 
Create Date: 2022-09-21 15:31:54.224910

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cb55c7d02aa0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'foo',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('parent_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('title', sa.String(length=256), nullable=True),
        sa.Column('registered_in', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['parent_id'], ['foo.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('foo')
    # ### end Alembic commands ###
